### ISSUE TITLE
Cannot install asyncari from pip

### ISSUE THREAD

**Issue by Elektordi** [M-o-a-T/asyncari#11]
Hello,

I'm unable to install asyncari from pip. 
I'm using Python 3.10.12 on Ubuntu 22.04.4 LTS.

Here is the error (tested on an empty venv):

```
Collecting asks>=2.2
[...]
      ModuleNotFoundError: No module named 'h11'
```

If I manually install h11, I have another error:

```
Collecting asks>=2.2
[...]
      ModuleNotFoundError: No module named 'anyio'
```

If I manually install anyio, I have another error:

```
Collecting asks>=2.2
[...]
      ImportError: cannot import name 'create_semaphore' from 'anyio' (/tmp/venv/lib/python3.10/site-packages/anyio/__init__.py)
```

The only working combination I found was installing: "asks==3.0.0" "asyncari==0.10.11" but I hit some bugs which have been already fixed in asyncari but I cannot upgrade... :(

Do you have any solution to install/upgrade asyncari ?

**Comment by Elektordi** [comment]
I found how to ask pip where the conflict is:
> ERROR: Cannot install asks==3.0.0 and asyncari==0.10.16 because these package versions have conflicting dependencies.
> The conflict is caused by:
>    asks 3.0.0 depends on anyio~=3.0
>    asyncari 0.10.16 depends on anyio>=4

**Comment by smurfix** [comment]
Well, that looks like asks needs updating. Thus closing here.

**Comment by Elektordi** [comment]
But since your lib depends on asks, there is no way of using asyncari 0.10.16 currently?
